export const ADD_EXPENSE = "ADD_EXPENSE";
export const REMOVE_EXPENSE = "REMOVE_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";

export const SET_TEXT_FILTER = "SET_TEXT_FILTER";
export const SET_SORT_BY = "SET_SORT_BY";
export const SET_START_DATE_FILTER = "SET_START_DATE_FILTER";
export const SET_END_DATE_FILTER = "SET_END_DATE_FILTER";
